[default]
[soc_sim]
homePath = $SPLUNK_DB/soc_sim/db
coldPath = $SPLUNK_DB/soc_sim/colddb
thawedPath = $SPLUNK_DB/soc_sim/thaweddb
datatype = event

[soc_notables]
homePath   = $SPLUNK_DB/soc_notables/db
coldPath   = $SPLUNK_DB/soc_notables/colddb
thawedPath = $SPLUNK_DB/soc_notables/thaweddb
